export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATE_INITIALIZED = 'AUTHENTICATE_INITIALIZED';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE';
export const AUTHENTICATE_LOGOUT = 'AUTHENTICATE_LOGOUT';
export const AUTHENTICATE_RELOAD = 'AUTHENTICATE_RELOAD';

export const FETCH_ORDER_ITEMS = 'FETCH_ORDER_ITEMS';
export const FETCH_ORDER_ITEMS_INITIALIZED = 'FETCH_ORDER_ITEMS_INITIALIZED';
export const FETCH_ORDER_ITEMS_SUCCESS = 'FETCH_ORDER_ITEMS_SUCCESS';
export const FETCH_ORDER_ITEMS_FAILURE = 'FETCH_ORDER_ITEMS_FAILURE';

export const ADD_ORDER_ITEMS = 'ADD_ORDER_ITEMS';
export const REMOVE_ORDER_ITEMS = 'REMOVE_ORDER_ITEMS';

export const SAVE_ORDER = 'SAVE_ORDER';
export const SAVE_ORDER_INITIALIZED = 'SAVE_ORDER_INITIALIZED';
export const SAVE_ORDER_SUCCESS = 'SAVE_ORDER_SUCCESS';
export const SAVE_ORDER_FAILURE = 'SAVE_ORDER_FAILURE';

export const FETCH_ORDERS_ADMIN = 'FETCH_ORDERS_ADMIN';
export const FETCH_ORDERS_ADMIN_INITIZALITED = 'FETCH_ORDERS_ADMIN_INITIZALITED';
export const FETCH_ORDERS_ADMIN_SUCCESS = 'FETCH_ORDERS_ADMIN_SUCCESS';
export const FETCH_ORDERS_ADMIN_FAILURE = 'FETCH_ORDERS_ADMIN_FAILURE';
